#Đánh version phiên bản YAML file của CircleCI
version: 2.1

# Khai báo các bước thực hiên
jobs:
# Job số 1 là đặt npm build
  build_dependencies:
 # Dùng docker image để giả lập môi trường nodejs để chạy lệnh npm install
    docker:
      - image: circleci/node:12
    # Các bước mà nó sẽ thực hiện trong job đầu tiên  
    steps:
      # Sao chép src code từ repository
      - checkout
      # Chạy câu lênh
      - run:
          name: Install npm dependencies
          command: |
            npm install --save

# Job số 2 là đặt build dọcer image
  build_docker_image:
    docker:
      - image: circleci/node:12
    # Các bước mà nó sẽ thực hiện trong job số 2
    steps:
      - checkout
      # Chuẩn bị môi trường Docker để build docker images
      - setup_remote_docker:
          docker_layer_caching: true
      # Chạy câu lệnh gì 
      - run:
          name: Build docker image
          command: |
            docker build -t lennguyen03/react-cicd-test .



# Job số 3 là đặt build dọcer image
  push_docker_image_to_dockerhub:
    docker:
      - image: circleci/node:12
    # Các bước mà nó sẽ thực hiện trong job số 3
    steps:
      - checkout
      # Chuẩn bị môi trường Docker để build docker images
      - setup_remote_docker:
          docker_layer_caching: true
      # Chạy câu lệnh gì 
      - run:
          name: Push docker image to docker hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u lennguyen03 --password-stdin
            docker push lennguyen03/react-cicd-test:v1

# Phần định nghĩa các quy trình mà các công việc được định nghĩa trước đó 
workflows:
  build_dependencies:
    jobs:
      - build_dependencies
      - build_docker_image
      - push_docker_image_to_dockerhub