version: 2.1

jobs:
  build:
    docker:
      - image: node:14  # Use an appropriate Node.js version
    steps:
      - checkout  # Check out your source code
      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Build React app
          command: npm run build

      - setup_remote_docker:
          version: 20.10.8  # Specify the Docker version you want to use

      - run:
          name: Build Docker image
          command: |
            docker build -t your-image-name:latest .


      - run:
          name: View docker images
          command: |
            docker images  
          # Optional, for debugging

      # - run:
      #     name: Build Docker image
      #     command: |
      #       docker build -t your-image-name:latest .
      #       docker images  # Optional, for debugging

      - run:
          name: Push Docker image to a Docker HUB
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push your-image-name:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build